[project]
authors = ["xupremix <xupremix.me@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Units of measurement"
name = "uom"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
